const fs = require('fs');
const path = require('path');

const GALLERY_DIR = path.join(__dirname, 'gallery');
const OUTPUT_FILE = path.join(__dirname, 'gallery-data.js');
const IMAGE_EXT = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.svg'];

function scanGallery() {
  if (!fs.existsSync(GALLERY_DIR)) {
    fs.mkdirSync(GALLERY_DIR, { recursive: true });
  }
  const files = fs.readdirSync(GALLERY_DIR);
  const images = files
    .filter(f => {
      const ext = path.extname(f).toLowerCase();
      return IMAGE_EXT.includes(ext) && !f.startsWith('.');
    })
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));

  const content = `/* auto-generated by build-gallery.js — не редактируй вручную */
window.GALLERY_FILES = ${JSON.stringify(images, null, 2)};
`;
  fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
  console.log('gallery-data.js обновлён:', images.length, 'файлов:', images.join(', ') || '(пусто)');
}

scanGallery();
